import { type Project } from '@/types';

export const allProjects: Project[] = [
    {
        id: 1,
        title: 'Ngambis-API',
        description: 'API RESTful untuk manajemen project kolaborasi dan otentikasi. Membutuhkan dokumentasi yang rapi dan pengujian unit yang kuat.',
        tags: ['Node.js', 'Express', 'MongoDB'],
        contributor: 'Rizki',
        href: '#',
        rolesNeeded: ['Backend Dev', 'QA Tester'],
    },
    {
        id: 2,
        title: 'Ngambishub-Docs',
        description: 'Membangun sistem dokumentasi yang modern dan interaktif menggunakan Nextra. Fokus pada kecepatan load dan SEO.',
        tags: ['Next.js', 'MDX'],
        contributor: 'Santi',
        href: '#',
        rolesNeeded: ['Technical Writer', 'Frontend Dev'],
    },
    {
        id: 3,
        title: 'Mobile UI Kit',
        description: 'Kumpulan komponen UI untuk aplikasi mobile React Native. Memerlukan fokus pada aksesibilitas dan desain modular.',
        tags: ['React Native', 'Expo'],
        contributor: 'Budi',
        href: '#',
        rolesNeeded: ['UI/UX Designer', 'React Native Dev'],
    },
    {
        id: 4,
        title: 'AI Chatbot Prototype',
        description: 'Chatbot berbasis LLM sederhana untuk customer support. Perlu diintegrasikan dengan layanan cloud seperti Google Gemini.',
        tags: ['Python', 'Flask', 'OpenAI'],
        contributor: 'Dewi',
        href: '#',
        rolesNeeded: ['ML Engineer', 'Data Scientist'],
    },
    {
        id: 5,
        title: 'E-commerce Backend',
        description: 'Backend layanan e-commerce dengan Laravel dan MySQL. Fokus pada keamanan transaksi dan skalabilitas.',
        tags: ['Laravel', 'MySQL', 'PHP'],
        contributor: 'Agus',
        href: '#',
        rolesNeeded: ['Laravel Dev', 'DevOps Engineer'],
    },
    {
        id: 6,
        title: 'Game Kuis Sederhana',
        description: 'Permainan kuis interaktif berbasis web (Vanilla JS) dengan sistem skor. Membutuhkan visual yang menarik.',
        tags: ['HTML', 'CSS', 'JavaScript'],
        contributor: 'Fajar',
        href: '#',
        rolesNeeded: ['Game Designer', 'Frontend Dev'],
    },
    {
        id: 7,
        title: 'Monitoring Dashboard',
        description: 'Dashboard real-time untuk memantau metrik server. Perlu visualisasi data yang canggih menggunakan D3.js.',
        tags: ['React', 'D3.js', 'WebSockets'],
        contributor: 'Gina',
        href: '#',
        rolesNeeded: ['Data Viz Expert', 'Backend Dev'],
    },
    {
        id: 8,
        title: 'Alat Desain Figma',
        description: 'Plugin Figma untuk menghasilkan palet warna otomatis berdasarkan tren terkini. Membutuhkan integrasi API Figma.',
        tags: ['Figma API', 'TypeScript'],
        contributor: 'Hadi',
        href: '#',
        rolesNeeded: ['Figma Expert', 'TypeScript Dev'],
    },
    {
        id: 9,
        title: 'Ngambishub Landing Page V2',
        description: 'Desain dan kode landing page utama yang lebih modern dan SEO-friendly. Memanfaatkan fitur Next.js terbaru.',
        tags: ['React', 'Tailwind', 'Shadcn'],
        contributor: 'Indra',
        href: '#',
        rolesNeeded: ['Copywriter', 'SEO Specialist'],
    },
    {
        id: 10,
        title: 'CLI Project Starter',
        description: 'Alat baris perintah untuk memulai proyek baru dengan cepat. Membutuhkan logika parsing argumen yang kuat.',
        tags: ['Golang', 'CLI'],
        contributor: 'Joko',
        href: '#',
        rolesNeeded: ['Golang Dev', 'Technical Writer'],
    },
];
